### PR TITLE
Update Social Services ministers

### PR DESCRIPTION
**Pull request by svict4**

### CODE REVIEW

**Comment by svict4** [comment]
@chris820 @bluevikstar

**Comment by svict4** [comment]
Don't merge yet please, there's a lot more to fix

**Comment by svict4** [comment]
Just discovered https://github.com/govau/australia-gov-au-directory-generator
I'll investigate editing the data there.

**Comment by gordjw** [comment]
Hey @svict4, thanks for the PR, that's awesome!

The directory generator is a prototype only at the moment. For the time being, we're instead looking to send people over to directory.gov.au, that being the actual source of truth and accurate.

I'm going to merge this into develop branch, but if you find any other content changes, we'd love to have them :)

**Pull request merged**
